services:
  profile-db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile
    volumes:
      - profile-data:/var/lib/mysql
    ports:
      - "3306:3306"

  iam-db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iam
    volumes:
      - iam-data:/var/lib/mysql
    ports:
      - "3307:3306"

  pet-db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet
    volumes:
      - pet-data:/var/lib/mysql
    ports:
      - "3308:3306"

  communication-db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: communication
    volumes:
      - communication-data:/var/lib/mysql
    ports:
      - "3309:3306"

  subscription-billing-db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subscription-billing
    volumes:
      - subscription-billing-data:/var/lib/mysql
    ports:
      - "3310:3306"

  tracking-db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracking
    volumes:
      - tracking-data:/var/lib/mysql
    ports:
      - "3311:3306"

volumes:
  profile-data:
  iam-data:
  pet-data:
  communication-data:
  subscription-billing-data:
  tracking-data: